name: Docker Remote Deployment
description: Ação do Github para implantação de projetos utilizando Docker-compose ou Swarm.
inputs:
  remote_docker_host:
    description: Remote Docker host ie (user@host).
    required: true
  remote_docker_port:
    description: Remote Docker ssh port ie (22).
    required: false
    default: '22'
  ssh_public_key:
    description: Remote Docker SSH public key eg (~/.ssh/rsa_id.pub).
    required: true
  ssh_private_key:
    description: SSH private key used to connect to the docker host eg (~/.ssh/rsa_id).
    required: true
  args:
    description: Deployment command args.
    required: true
  deployment_mode:
    description: Deployment mode either docker-swarm or docker-compose. Default is docker-compose.
    required: false
  stack_file_name:
    description: Docker stack file used. Default is docker-compose.yml.
    required: false
  docker_registry_username:
    description: The docker registry username.
    required: false
  docker_registry_token:
    description: The docker registry password.
    required: false
  docker_registry_uri:
    description: The docker registry URI. Default is https://registry.hub.docker.com.
    required: false
  docker_script:
    description: The script to run single service
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green
